In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [40]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [60]:
df = pd.read_csv('/content/drive/MyDrive/data/busan/지역별_관광지_검색순위.csv')
df2 = pd.read_csv('/content/drive/MyDrive/data/busan/부산광역시_지역화폐(동백전) 가맹점 현황_20221222.csv', encoding = 'cp949')
df3 = pd.read_csv('/content/drive/MyDrive/data/busan/지역별_관광지_검색순위_식음료.csv')
df4 = pd.read_csv('/content/drive/MyDrive/data/busan/지역별_관광지_검색순위_숙박.csv')

In [57]:
df['중분류 카테고리'].value_counts()

문화관광     183
쇼핑       146
자연관광      62
기타관광      40
레저스포츠     31
역사관광      29
체험관광       9
Name: 중분류 카테고리, dtype: int64

In [59]:
df3['중분류 카테고리'].value_counts()

음식    500
Name: 중분류 카테고리, dtype: int64

In [76]:
result1 = pd.concat([df, df3])
result2 = pd.concat([result1, df4])
result2

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수
0,1,신세계백화점센텀시티점,부산광역시,해운대구,부산 해운대구 센텀남대로 35-0,쇼핑,백화점,"559,499"
1,2,김해공항국내선청사,부산광역시,강서구,부산 강서구 공항진입로 108-0,기타관광,교통시설,"446,879"
2,3,롯데백화점부산본점,부산광역시,부산진구,부산 부산진구 가야대로 772-0,쇼핑,백화점,"381,864"
3,4,김해국제공항,부산광역시,강서구,부산 강서구 공항진입로 108-0,기타관광,교통시설,"321,903"
4,5,광안리해수욕장,부산광역시,수영구,부산 수영구 광안해변로 219-0,자연관광,자연경관(하천/해양),"261,818"
...,...,...,...,...,...,...,...,...
495,496,하운드호텔정관점,부산광역시,기장군,부산 기장군 산단1로 98-11,숙박,호텔,983
496,497,모모쥬스,부산광역시,해운대구,부산 해운대구 해운대해변로209번길 12-0,숙박,모텔,978
497,497,아이유모텔,부산광역시,연제구,부산 연제구 월드컵대로99번길 31-0,숙박,모텔,978
498,499,제이모텔,부산광역시,사상구,부산 사상구 대동로 297-0,숙박,모텔,976
499,500,브이호텔,부산광역시,중구,부산 중구 보수대로 8-3,숙박,호텔,971

In [77]:
result2['검색건수'] = result2['검색건수'].str.replace(',','')
result2['검색건수'] = result2['검색건수'].astype('int')

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수
499,500,브이호텔,부산광역시,중구,부산 중구 보수대로 8-3,숙박,호텔,971
498,499,제이모텔,부산광역시,사상구,부산 사상구 대동로 297-0,숙박,모텔,976
496,497,모모쥬스,부산광역시,해운대구,부산 해운대구 해운대해변로209번길 12-0,숙박,모텔,978
497,497,아이유모텔,부산광역시,연제구,부산 연제구 월드컵대로99번길 31-0,숙박,모텔,978
495,496,하운드호텔정관점,부산광역시,기장군,부산 기장군 산단1로 98-11,숙박,호텔,983
...,...,...,...,...,...,...,...,...
4,5,광안리해수욕장,부산광역시,수영구,부산 수영구 광안해변로 219-0,자연관광,자연경관(하천/해양),261818
3,4,김해국제공항,부산광역시,강서구,부산 강서구 공항진입로 108-0,기타관광,교통시설,321903
2,3,롯데백화점부산본점,부산광역시,부산진구,부산 부산진구 가야대로 772-0,쇼핑,백화점,381864
1,2,김해공항국내선청사,부산광역시,강서구,부산 강서구 공항진입로 108-0,기타관광,교통시설,446879
0,1,신세계백화점센텀시티점,부산광역시,해운대구,부산 해운대구 센텀남대로 35-0,쇼핑,백화점,559499

In [78]:
df_new = result2.sort_values(by='검색건수',ascending = False)
df_new.head(50)

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수
0,1,신세계백화점센텀시티점,부산광역시,해운대구,부산 해운대구 센텀남대로 35-0,쇼핑,백화점,559499
1,2,김해공항국내선청사,부산광역시,강서구,부산 강서구 공항진입로 108-0,기타관광,교통시설,446879
2,3,롯데백화점부산본점,부산광역시,부산진구,부산 부산진구 가야대로 772-0,쇼핑,백화점,381864
3,4,김해국제공항,부산광역시,강서구,부산 강서구 공항진입로 108-0,기타관광,교통시설,321903
4,5,광안리해수욕장,부산광역시,수영구,부산 수영구 광안해변로 219-0,자연관광,자연경관(하천/해양),261818
5,6,해운대해수욕장,부산광역시,해운대구,부산 해운대구 해운대해변로 264-0,자연관광,자연경관(하천/해양),261722
6,7,코스트코홀세일부산점,부산광역시,수영구,부산 수영구 구락로 137-0,쇼핑,대형마트,260036
7,8,송정해수욕장,부산광역시,해운대구,부산 해운대구 송정해변로 62-0,자연관광,자연경관(하천/해양),244851
8,9,해동용궁사,부산광역시,기장군,부산 기장군 용궁길 86-0,역사관광,종교성지,199253
9,10,롯데백화점광복점,부산광역시,중구,부산 중구 중앙대로 2-0,쇼핑,백화점,172097
0,1,아난티힐튼부산,부산광역시,기장군,부산 기장군 기장해안로 268-32,숙박,호텔,152941
10,11,롯데프리미엄아울렛동부산점,부산광역시,기장군,부산 기장군 기장해안로 147-0,쇼핑,쇼핑몰,152655
11,12,NC백화점서면점,부산광역시,부산진구,부산 부산진구 동천로 92-0,쇼핑,백화점,150114
12,13,다대포해수욕장,부산광역시,사하구,부산 사하구 몰운대1길 14-0,자연관광,자연경관(하천/해양),144834
13,14,롯데월드어드벤처부산,부산광역시,기장군,부산 기장군 동부산관광로 42-0,문화관광,테마공원,134067
14,15,이마트트레이더스연산점,부산광역시,연제구,부산 연제구 좌수영로 241-0,쇼핑,대형마트,131370
15,16,기장시장,부산광역시,기장군,부산 기장군 읍내로104번길 16-0,쇼핑,시장,124470
16,17,태종대,부산광역시,영도구,부산 영도구 전망로 24-0,역사관광,역사유적지,121311
17,18,송도해수욕장,부산광역시,서구,부산 서구,자연관광,자연경관(하천/해양),119540
18,19,롯데백화점동래점,부산광역시,동래구,부산 동래구 중앙대로 1393-0,쇼핑,백화점,114686
19,20,반여농산물도매시장,부산광역시,해운대구,부산 해운대구 수영강변대로 626-0,쇼핑,시장,113616
20,21,국제시장,부산광역시,중구,부산 중구 국제시장2길 25-0,쇼핑,시장,112193
1,2,파라다이스호텔부산,부산광역시,해운대구,부산 해운대구 해운대해변로 296-0,숙박,호텔,111872
21,22,이케아동부산점,부산광역시,기장군,부산 기장군 동부산관광3로 17-0,쇼핑,쇼핑몰,109737
2,3,한화리조트해운대,부산광역시,해운대구,부산 해운대구 마린시티3로 52-0,숙박,콘도미니엄,103401
0,1,칠암사계,부산광역시,기장군,부산 기장군 칠암1길 7-10,음식,카페/찻집,100578
22,23,이마트트레이더스명지점,부산광역시,강서구,부산 강서구 명지국제6로 168-0,쇼핑,대형마트,99616
23,24,자갈치시장,부산광역시,중구,부산 중구 자갈치해안로 52-0,쇼핑,시장,98673
24,25,이마트해운대점,부산광역시,해운대구,부산 해운대구 좌동순환로 511-0,쇼핑,대형마트,95167
25,26,이마트문현점,부산광역시,남구,부산 남구 전포대로91번길 47-0,쇼핑,대형마트,91087
26,27,롯데마트화명점,부산광역시,북구,부산 북구 화명대로 47-0,쇼핑,대형마트,89824
27,28,BEXCO,부산광역시,해운대구,부산 해운대구 APEC로 55-0,문화관광,전시시설,89716
28,29,신세계프리미엄아울렛부산점,부산광역시,기장군,부산 기장군 정관로 1133-0,쇼핑,쇼핑몰,88702
29,30,신세계센텀시티몰,부산광역시,해운대구,부산 해운대구 센텀4로 15-0,쇼핑,백화점,88631
30,31,벡스코제1전시장,부산광역시,해운대구,부산 해운대구 APEC로 55-0,문화관광,전시시설,87725
31,32,메가마트동래점,부산광역시,동래구,부산 동래구 충렬대로 197-0,쇼핑,대형마트,87452
32,33,이마트트레이더스서면점,부산광역시,부산진구,부산 부산진구 시민공원로 31-0,쇼핑,대형마트,86358
33,34,이마트연제점,부산광역시,연제구,부산 연제구 연수로 89-0,쇼핑,대형마트,80580
34,35,일광해수욕장,부산광역시,기장군,부산 기장군 삼성3길 0-0,자연관광,자연경관(하천/해양),80397
35,36,부산시민공원,부산광역시,부산진구,부산 부산진구 시민공원로 73-0,문화관광,도시공원,78895
36,37,해운대블루라인파크미포정거장,부산광역시,해운대구,부산 해운대구 달맞이길62번길 13-0,기타관광,기타관광,78421
37,38,이마트금정점,부산광역시,금정구,부산 금정구 중앙대로1841번길 24-0,쇼핑,대형마트,77997
38,39,롯데백화점센텀시티점,부산광역시,해운대구,부산 해운대구 센텀남대로 59-0,쇼핑,백화점,77908
39,40,홈플러스아시아드점,부산광역시,연제구,부산 연제구 종합운동장로 7-0,쇼핑,대형마트,77360
40,41,대변항,부산광역시,기장군,부산 기장군 기장해안로 0-0,자연관광,자연경관(하천/해양),74298
41,42,범어사,부산광역시,금정구,부산 금정구 범어사로 250-0,역사관광,종교성지,73779
42,43,이마트사상점,부산광역시,사상구,부산 사상구 광장로 17-0,쇼핑,대형마트,73612
43,44,신선대부두,부산광역시,남구,부산 남구,자연관광,자연경관(하천/해양),72716
44,45,현대백화점부산점,부산광역시,동구,부산 동구 범일로 125-0,쇼핑,백화점,71870
45,46,엄궁농산물도매시장,부산광역시,사상구,부산 사상구 농산물시장로9번길 11-0,쇼핑,시장,71059

In [80]:
df2.head()

,순번,가맹점명,도로명,지번,위도,경도,데이터기준일자
0,1,고봉민김밥인,부산 영도구 와치로 250 (동삼동) 1층,NaN,35.075315,129.068770,2022-12-22
1,2,미사랑스킨앤바디,"부산 사하구 승학로224번길 10 ,1층(괴정동)",NaN,35.101239,128.990313,2022-12-22
2,3,피자스쿨 부산재송점,부산 해운대구 재반로 182 비둘기맨션상가 B동 가호 (재송동),NaN,35.193467,129.130557,2022-12-22
3,4,미스터피자아시아드2호점,"부산 연제구 월드컵대로 232 2층 (거제동,거벌빌등)",NaN,35.189890,129.071940,2022-12-22
4,5,성원칼국수,부산 부산진구 냉정로 220-1 (개금동),NaN,35.150897,129.023928,2022-12-22

In [58]:
df_cul_nat = df[(df['중분류 카테고리'] == '문화관광') | (df['중분류 카테고리'] == '자연관광')]
df_cul_nat

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수
4,5,광안리해수욕장,부산광역시,수영구,부산 수영구 광안해변로 219-0,자연관광,자연경관(하천/해양),"261,818"
5,6,해운대해수욕장,부산광역시,해운대구,부산 해운대구 해운대해변로 264-0,자연관광,자연경관(하천/해양),"261,722"
7,8,송정해수욕장,부산광역시,해운대구,부산 해운대구 송정해변로 62-0,자연관광,자연경관(하천/해양),"244,851"
12,13,다대포해수욕장,부산광역시,사하구,부산 사하구 몰운대1길 14-0,자연관광,자연경관(하천/해양),"144,834"
13,14,롯데월드어드벤처부산,부산광역시,기장군,부산 기장군 동부산관광로 42-0,문화관광,테마공원,"134,067"
...,...,...,...,...,...,...,...,...
491,492,75광장,부산광역시,영도구,부산 영도구,문화관광,도시공원,"2,060"
494,495,조은극장1관,부산광역시,중구,부산 중구 구덕로34번길 4-0,문화관광,공연시설,"2,040"
495,496,메가박스해운대,부산광역시,해운대구,부산 해운대구 해운대로 813-0,문화관광,공연시설,"2,033"
497,498,메가박스부산대,부산광역시,금정구,부산 금정구 장전로12번길 55-0,문화관광,공연시설,"2,029"
499,500,비콘그라운드,부산광역시,수영구,부산 수영구 망미번영로 0-0,문화관광,기타문화관광지,"2,015"

In [8]:
df2[df2['관광지명'].str.contains('광안리')]

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수
213,214,커피스미스광안리점,부산광역시,수영구,부산 수영구 광안해변로255번길 5-0,음식,카페/찻집,"7,139"
397,398,스타벅스광안리점,부산광역시,수영구,부산 수영구 광안해변로 247-0,음식,카페/찻집,"4,540"

In [9]:
df2['소분류 카테고리'].value_counts()

한식       162
카페/찻집    131
전문음식     110
간이음식      59
외국식       37
음식점기타      1
Name: 소분류 카테고리, dtype: int64

In [10]:
df_cafe = df2[df2['소분류 카테고리'] == '카페/찻집']
df_cafe

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수
0,1,칠암사계,부산광역시,기장군,부산 기장군 칠암1길 7-10,음식,카페/찻집,"100,578"
1,2,웨이브온커피,부산광역시,기장군,부산 기장군 해맞이로 286-0,음식,카페/찻집,"66,691"
2,3,피아크카페앤베이커리,부산광역시,영도구,부산 영도구 해양로195번길 180-0,음식,카페/찻집,"60,904"
7,8,스타벅스명지강변DT점,부산광역시,강서구,부산 강서구 르노삼성대로 620-0,음식,카페/찻집,"32,333"
10,11,헤이든,부산광역시,기장군,부산 기장군 문오성길 22-0,음식,카페/찻집,"30,271"
...,...,...,...,...,...,...,...,...
479,480,쿼피집,부산광역시,사상구,부산 사상구 사상로356번길 16-0,음식,카페/찻집,"3,874"
480,481,로와맨션,부산광역시,기장군,부산 기장군 학리2길 6-0,음식,카페/찻집,"3,871"
487,488,아시오,부산광역시,부산진구,부산 부산진구 월드컵대로472번길 1-0,음식,카페/찻집,"3,821"
493,494,카페노티드부산해운대,부산광역시,해운대구,부산 해운대구 구남로 17-0,음식,카페/찻집,"3,782"
497,498,탐앤탐스블랙달맞이점,부산광역시,해운대구,부산 해운대구 달맞이길 213-0,음식,카페/찻집,"3,761"

In [11]:
df_cafe['지역화폐 사용가능'] = 'o'

<ipython-input-11-b93d5880b6d9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cafe['지역화폐 사용가능'] = 'o'

In [12]:
df_cafe

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수,지역화폐 사용가능
0,1,칠암사계,부산광역시,기장군,부산 기장군 칠암1길 7-10,음식,카페/찻집,"100,578",o
1,2,웨이브온커피,부산광역시,기장군,부산 기장군 해맞이로 286-0,음식,카페/찻집,"66,691",o
2,3,피아크카페앤베이커리,부산광역시,영도구,부산 영도구 해양로195번길 180-0,음식,카페/찻집,"60,904",o
7,8,스타벅스명지강변DT점,부산광역시,강서구,부산 강서구 르노삼성대로 620-0,음식,카페/찻집,"32,333",o
10,11,헤이든,부산광역시,기장군,부산 기장군 문오성길 22-0,음식,카페/찻집,"30,271",o
...,...,...,...,...,...,...,...,...,...
479,480,쿼피집,부산광역시,사상구,부산 사상구 사상로356번길 16-0,음식,카페/찻집,"3,874",o
480,481,로와맨션,부산광역시,기장군,부산 기장군 학리2길 6-0,음식,카페/찻집,"3,871",o
487,488,아시오,부산광역시,부산진구,부산 부산진구 월드컵대로472번길 1-0,음식,카페/찻집,"3,821",o
493,494,카페노티드부산해운대,부산광역시,해운대구,부산 해운대구 구남로 17-0,음식,카페/찻집,"3,782",o
497,498,탐앤탐스블랙달맞이점,부산광역시,해운대구,부산 해운대구 달맞이길 213-0,음식,카페/찻집,"3,761",o

In [13]:
df_cafe.head(10)

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수,지역화폐 사용가능
0,1,칠암사계,부산광역시,기장군,부산 기장군 칠암1길 7-10,음식,카페/찻집,"100,578",o
1,2,웨이브온커피,부산광역시,기장군,부산 기장군 해맞이로 286-0,음식,카페/찻집,"66,691",o
2,3,피아크카페앤베이커리,부산광역시,영도구,부산 영도구 해양로195번길 180-0,음식,카페/찻집,"60,904",o
7,8,스타벅스명지강변DT점,부산광역시,강서구,부산 강서구 르노삼성대로 620-0,음식,카페/찻집,"32,333",o
10,11,헤이든,부산광역시,기장군,부산 기장군 문오성길 22-0,음식,카페/찻집,"30,271",o
13,14,비아조,부산광역시,강서구,부산 강서구 식만로 164-0,음식,카페/찻집,"28,549",o
15,16,코랄라니,부산광역시,기장군,부산 기장군 기장해안로 32-0,음식,카페/찻집,"25,349",o
19,20,피크스퀘어,부산광역시,기장군,부산 기장군 기장해안로 864-0,음식,카페/찻집,"22,582",o
22,23,스타벅스동명대DT점,부산광역시,남구,부산 남구 신선로 423-0,음식,카페/찻집,"20,157",o
23,24,모모스로스터리&커피바,부산광역시,영도구,부산 영도구 봉래나루로 160-0,음식,카페/찻집,"19,923",o

In [33]:
df_starbuck = df_cafe[df_cafe['관광지명'].str.contains('스타벅스')]
df_starbuck

,순위,관광지명,광역시/도,시/군/구,도로명주소,중분류 카테고리,소분류 카테고리,검색건수,지역화폐 사용가능
7,8,스타벅스명지강변DT점,부산광역시,강서구,부산 강서구 르노삼성대로 620-0,음식,카페/찻집,"32,333",x
22,23,스타벅스동명대DT점,부산광역시,남구,부산 남구 신선로 423-0,음식,카페/찻집,"20,157",o
35,36,스타벅스해운대달맞이DT점,부산광역시,해운대구,부산 해운대구 달맞이길 57-0,음식,카페/찻집,"17,057",o
38,39,스타벅스화명강변DT점,부산광역시,북구,부산 북구 금곡대로 77-0,음식,카페/찻집,"16,527",o
46,47,스타벅스동부산DT점,부산광역시,기장군,부산 기장군 기장해안로 56-0,음식,카페/찻집,"14,818",o
56,57,스타벅스부산재송DT점,부산광역시,해운대구,부산 해운대구 해운대로 189-0,음식,카페/찻집,"13,393",o
59,60,스타벅스기장역DT점,부산광역시,기장군,부산 기장군 기장대로 527-0,음식,카페/찻집,"13,221",o
60,61,스타벅스을숙도강변DT점,부산광역시,사하구,부산 사하구 하신번영로 381-6,음식,카페/찻집,"13,209",o
101,102,스타벅스사상주례DT점,부산광역시,사상구,부산 사상구 백양대로 520-0,음식,카페/찻집,"10,362",o
119,120,스타벅스동서대DT점,부산광역시,사상구,부산 사상구 가야대로 338-0,음식,카페/찻집,"9,572",o
133,133,스타벅스수영망미DT점,부산광역시,수영구,부산 수영구 과정로 68-0,음식,카페/찻집,"9,183",o
151,152,스타벅스동래미남DT점,부산광역시,동래구,부산 동래구 충렬대로 101-0,음식,카페/찻집,"8,622",o
159,160,스타벅스부산송정비치점,부산광역시,해운대구,부산 해운대구 송정해변로 36-0,음식,카페/찻집,"8,458",o
161,162,스타벅스부산안락DT점,부산광역시,동래구,부산 동래구 충렬대로 446-0,음식,카페/찻집,"8,445",o
162,163,스타벅스수영강변DT점,부산광역시,해운대구,부산 해운대구 수영강변대로 516-0,음식,카페/찻집,"8,409",o
170,171,스타벅스금정구청DT점,부산광역시,금정구,부산 금정구 중앙대로 1730-0,음식,카페/찻집,"8,276",o
176,177,스타벅스온천장역DT점,부산광역시,금정구,부산 금정구 식물원로 13-0,음식,카페/찻집,"8,110",o
179,180,스타벅스금정남산동DT점,부산광역시,금정구,부산 금정구 중앙대로 1989-0,음식,카페/찻집,"8,077",o
181,182,스타벅스부산정관점,부산광역시,기장군,부산 기장군 정관로 579-0,음식,카페/찻집,"8,032",o
212,212,스타벅스영도청학DT점,부산광역시,영도구,부산 영도구 태종로 373-0,음식,카페/찻집,"7,153",o
223,224,스타벅스삼락강변DT점,부산광역시,사상구,부산 사상구 낙동대로 1306-0,음식,카페/찻집,"6,854",o
241,242,스타벅스해운대달맞이점,부산광역시,해운대구,부산 해운대구 달맞이길 189-0,음식,카페/찻집,"6,536",o
247,248,스타벅스용호동W스퀘어점,부산광역시,남구,부산 남구 분포로 145-0,음식,카페/찻집,"6,491",o
259,260,스타벅스부산교대역DT점,부산광역시,연제구,부산 연제구 중앙대로 1250-0,음식,카페/찻집,"6,238",o
263,264,스타벅스사하장림DT점,부산광역시,사하구,부산 사하구 을숙도대로 682-0,음식,카페/찻집,"6,234",o
302,303,스타벅스영도대교점,부산광역시,영도구,부산 영도구 태종로 39-0,음식,카페/찻집,"5,552",o
311,312,스타벅스명지오션시티점,부산광역시,강서구,부산 강서구 명지오션시티11로 66-0,음식,카페/찻집,"5,515",o
379,380,스타벅스명지국제신도시점,부산광역시,강서구,부산 강서구 명지국제5로 42-0,음식,카페/찻집,"4,733",o
397,398,스타벅스광안리점,부산광역시,수영구,부산 수영구 광안해변로 247-0,음식,카페/찻집,"4,540",o
422,423,스타벅스사상엄궁DT점,부산광역시,사상구,부산 사상구 낙동대로 744-0,음식,카페/찻집,"4,303",o
427,428,스타벅스부산덕천역점,부산광역시,북구,부산 북구 만덕대로 30-0,음식,카페/찻집,"4,244",o
439,440,스타벅스부산만덕DT점,부산광역시,북구,부산 북구 만덕대로 323-0,음식,카페/찻집,"4,182",o

카페 : 131개

* 지역화폐 사용 불가능
    * 스타벅스 : 32개
    * 코랄라니

* 애매한 것
    * 헤이든